### ISSUE TITLE
Docs: Wizard

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#113]
Write documentation on the wizard. This means detailing any api's or components it may use and any new features that it encompasses in terms of functionality. 

Write the documentation on this page:
https://github.com/SoftStackFactory/reboot/wiki/Wizard

**Comment by iamalx** [comment]
#113 Done with Documentation. Had trouble uploading my changes so i had to save them in a word doc instead.

https://github.com/SoftStackFactory/reboot/wiki/Wizard/_history
