### ISSUE TITLE
Flow: Wizard

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#117]
Create a wizard flow that details user interactions and possible actions. 

Use Google Doc's Drawings if you need a program to create flowcharts.

Upload the flowchart here:
https://github.com/SoftStackFactory/reboot/wiki/Flow:-Wizard

See An Example: 

![bank-teller-flowchart-template](https://user-images.githubusercontent.com/2165265/46907700-74ea5f80-cecb-11e8-9695-8f492f535247.png)

**Comment by khoadnguyen** [comment]
Assigning to you alex since you're most knowledgeable.

**Comment by iamalx** [comment]
Flow on wike; however I had issues uploading this.

**Comment by iamalx** [comment]
#171 flow finished; however I had issues uploading it.

**Comment by iamalx** [comment]
https://github.com/SoftStackFactory/reboot/wiki/Flow:-Wizard/_history
