### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#12]
**Describe the feature briefly:**
We need to create a Login page based off of the wireframes.

**What needs to be done?**
Layout and structure of the page need to be added.

**Where does this appear?**
`reboot/src/pages/login` only.

**Extra notes:*
None.

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/20 - link to the PR that resolves this issue.
