### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#13]
**Describe the feature briefly:**
We need to create a Dashboard page based off of the wireframes.

**What needs to be done?**
Layout and structure of the page need to be added.

**Where does this appear?**
`reboot/src/pages/dashboard` only.

**Extra notes:*
None.

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/21 - link to the PR that resolves this issue. The first comment is the wrong PR that I did to merge into master instead of dev.
