### ISSUE TITLE
Login-page Include more validators for password

### ISSUE THREAD

**Issue by iamalx** [SoftStackFactory/reboot#135]
**Describe the bug**
Not enough validation for  password input such as max  or min length 

**To Reproduce**
1. Go to 'Login age'
2. Click on 'password input field '
3. type: 'any character(only one)'
3b. type: enter a valid email on email field
4. See error:  both fields are validated even though password input field had only one character.
5. Repeat, and for input field type a long word.  

**Expected behavior**
The password input field needs to be invalid and show an error message (class.invalid) when only one character or more than 30 are typed.

**Additional comments**
Validator should be the same as register password validator

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/141 - link to the PR that resolves this issue
