### ISSUE TITLE
Data Model: Chart

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#156]
**What needs to be research?**
Research and outline the data flow for the Chart/Dashboard. This means:

- [x] What data does your page need? 
- [x] What does the data look like?
- [x] What data does your page/section output?
- [x] How is data on the form/slider processed?

**What are the deliverables?**
- [x] Quick write up here about how the page will consume that data & what happens if that data changes?
- [x] Create a wiki page titled: Data Model: Chart

**Comment by awstin17** [comment]
This is what I've come up with:

1) The only data we need to store is that one array of eight data points
2) We will create a chartProvider that will request the specific user's data array upon login.
3) That chart data array will always be located in the chartProvider and will be updated there from the sliders on the transition page
4) Upon logout, we will post whatever updates to the array in chartProvider to the database

**Comment by khoadnguyen** [comment]
Great, could you document this and write it up on a wiki page? Also, on there provide an example of what that data looks like.
