### ISSUE TITLE
Chart: Component

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#157]
**Describe the feature briefly:**
The chart on the dashboard/transition page is good, but we need to be able to make it into a component since we use it in more than one place (think DRY). This should probably be done in tandem with: https://github.com/SoftStackFactory/reboot/issues/156. 

**What needs to be done?**

- [x] Look at the chart and convert it into a component
- [x] Make it extensible enough to take in data and render (so don't use mock data).
- [x] Replace the new chart component in place of the current static chart.

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/163 - link to the PR that resolves this issue
