### ISSUE TITLE
Timeline Component: not responsive

### ISSUE THREAD

**Issue by phortonssf** [SoftStackFactory/reboot#165]
**Describe the bug**
When on a desktop the timeline component light green circles are going into the text in the below segment for each.

**To Reproduce**
1. Go to timeline page on a large screen
2. Look at circles and text.
3. See error

**Expected behavior**
The text should not have a circle over it.

**Screenshots**

![screen shot 2018-10-22 at 5 17 48 pm](https://user-images.githubusercontent.com/23040285/47326626-6e23c100-d61e-11e8-85b9-b43a5ca43ba0.png)

**Desktop (please complete the following information):**
 - OS:  Mac
 - Browser Chrome

**Comment by khoadnguyen** [comment]
@jal040 @phortonssf As far as I know we've only done iPad optimizations, but we should go ahead and fix this anyway.
