### ISSUE TITLE
Assessment Page: remove

### ISSUE THREAD

**Issue by phortonssf** [SoftStackFactory/reboot#166]
**Describe the bug**
_Peter's original note:_ 
> Nothing on the page. Also if we are going to use the page menu is on wrong side, right side vs left in the rest of app.

- We need to remove this page since it is no longer applicable to the application anymore. Let's remove all remnants of it entirely.

**Comment by khoadnguyen** [comment]
This page is no longer applicable since we changed the flow of the app. I'm going to change this issue so that this page gets removed.

**Comment by digitalkyopo** [comment]
I removed the page and it's references in app module on branch 166-assessment-page-remove. I didn't realize Austin had it already. The branch was pushed to the repo and we can merge after reviewing or we can use Austin's if he's already completed it. I noticed there was a spec file with a test in it and I was wondering if that was something we were going to be referencing soon that we might want to hold off removing for.

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/172 - link to the PR that resolves this issue

**Comment by khoadnguyen** [comment]
@awstin17 can we go ahead and restructure this page to be a testing example page. Let's just remove all the links and what not from the front end. If you need to go ahead and make a new branch, you can do that.

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/179 - This is the most recent PR to resolve the issue.
