### ISSUE TITLE
Timeline: UI Improvements. 

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#196]
**Describe the bug**
Fix styling issues on timeline page. 

- [x] Blue line issues on specific viewports
- [x] Status indicator for what step they're on (on same page)
- [x] Incorporating timeframes into checkpoints.
- [x] Status indicators for menu headers (completeness or done)

**Additional context**
Reference project charter if needed.

**Comment by papasmurf80** [comment]
Continued blue line/green dot theme out to bullet items

**Comment by khoadnguyen** [comment]
Looks good
