### ISSUE TITLE
Timeline: Adding the timeline content

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#197]
**Describe the feature briefly:**
We need a more complete list for the timeline page to be done. 

**What needs to be done?**
- [x] Refer to content docs for larger timeline data, import content to timeline 

**Where does this appear?**
Timeline Page

**Comment by papasmurf80** [comment]
Clarity needed from client regarding selection and cascade order of additional content

**Comment by papasmurf80** [comment]
Timeline data built out through final stage of program.
