### ISSUE TITLE
Timeline: Backend/API communication w/ Ionic

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#198]
**Describe the feature briefly:**
The timeline component needs to actually pull in user data. Let's research first and update the model that is on: https://github.com/SoftStackFactory/reboot/wiki/Data-Model:-Timeline-Content. 

**What needs to be done?**

- [x] Creating backend endpoint for timeline data
- [x] Pulling that timeline data into component
- [x] Formatting and displaying that data correctly 

**Where does this appear?**
Backend & Timeline page.

**Comment by papasmurf80** [comment]
Data is verified before handling. Successful save to back-end, progress is displayed as previously saved.
