### ISSUE TITLE
Resources: Wireframe and layout

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#199]
**Describe the feature briefly:**
Create a wireframe for the resource page and mock up a layout. 

**What needs to be done?**

- [x] Wireframe for resource page. 
- [x] Attach wireframe to issue here for review

**Where does this appear?**
New Resources page.

**Comment by ghost** [comment]
<img width="591" alt="screen shot 2018-11-14 at 8 55 06 pm" src="https://user-images.githubusercontent.com/41034772/48531106-ae5a1600-e84f-11e8-8fc0-215030b37bc6.png">

<img width="565" alt="screen shot 2018-11-14 at 8 55 31 pm" src="https://user-images.githubusercontent.com/41034772/48531123-bdd95f00-e84f-11e8-8c65-9e0f5cc137dd.png">

I mocked up the page to display cards. First card will describe the page briefly. Second one will display the lowest scored category and score number from the self assessment. Below that will loop through all of provided resources. Each card will have a 'learn more' link which will open a modal with an explanation of the resource and website link if any.

**Comment by khoadnguyen** [comment]
Great! 👍
