### ISSUE TITLE
Resources: Page creation in Ionic

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#200]
**What needs to be done?**
- [x] Generate a new resource page in ionic
- [x] Implement layout (HTML, CSS) outlined in wireframe issue: https://github.com/SoftStackFactory/reboot/issues/199
- Use mock data for any models or dynamic content that will be switched out later 

**Where does this appear?**
What parts of the application does this change?

**Comment by ghost** [comment]
Created Resource Page and implemented HTML/CSS. 
Also started Modal functionality.
