### ISSUE TITLE
Self Assessment: Page refactor and flow

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#202]
**What needs to be done?**
- [x] Wireframe of intended changes
- [x] Page creation and basic mockup for review
- [x] All associated styling for page layout.

**Where does this appear?**
Self Assessment page.

**Comment by WarrenG8** [comment]
![selfassessment](https://user-images.githubusercontent.com/20914759/48983084-430a1280-f09f-11e8-8b87-4349ba9cd2fb.png)
