### ISSUE TITLE
Self Assessment: Data Model and Improvements

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#203]
**Describe the feature briefly:**
We need to come together for a research task that involves settling the data model conversation for the self assessment and corresponding charts/resources section. Let's chat during class and see if we can hash it out, but bring a model if what you think your individual component/page requires and we can discuss it.

**Comment by brettwray** [comment]
For the chart, particularly on the history page having the data be date based would be ideal. What do you guys think? @colis123 @WarrenG8 
`dataModel = {
    "11/19/2018" : {
        career: number,
        finance: number,
        personalgrwoth: number,
        health: number,
        family: number,
        relationships: number,
        sociallife: number,
        attitude: number
    },
    "11/18/2018" : {
        career: number,
        finance: number,
        personalgrwoth: number,
        health: number,
        family: number,
        relationships: number,
        sociallife: number,
        attitude: number
    }
}`

**Comment by ghost** [comment]
Yeah good idea.

**Comment by khoadnguyen** [comment]
@colis123 were you able to made any progress in determining the data model we'll need to move forward? Let's keep the conversation going so others can solidify their data models moving forward.

**Comment by ghost** [comment]
This model works good. Which is what the current chart model looks like.
data2: object =
      {
        date: '11/11/18',
        data: [1, 3, 5, 3, 6, 7, 9, 8 ]
      }

**Comment by WarrenG8** [comment]
Hey guys,

Now that I have taken a closer look. I believe this would be the optimal
model:

assessments: {
"12/01/2018": { 'career': number, 'finance': number, 'personalgrowth':
number, 'health': number, 'family': number, 'relationships': number,
'sociallife': number, 'attitude': number }, "11/18/2018" : { 'career':
number, 'finance': number, 'personalgrowth': number, 'health': number,
'family': number, 'relationships': number, 'sociallife': number,
'attitude': number },
}

I think it might be easier to maintain going forward if others were to
inherit the app.

What do you guys think?

**Comment by WarrenG8** [comment]
or
data: {
"12/01/2018": { 'career': number, 'finance': number, 'personalgrowth':
number, 'health': number, 'family': number, 'relationships': number,
'sociallife': number, 'attitude': number }, "11/18/2018" : { 'career':
number, 'finance': number, 'personalgrowth': number, 'health': number,
'family': number, 'relationships': number, 'sociallife': number,
'attitude': number },
}

But we should probably use an object though.

**Comment by ghost** [comment]
Yeah that works. We would have to create a new end point right? Self assessment would POST the data and then the chart/resources can GET data and display>?
