### ISSUE TITLE
Dashboard: New news widget

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#207]
**Describe the feature briefly:**
We need a news widget for the dashboard that display relevant news for the user. This may use an RSS feed or some else to pull from. 

**What needs to be done?**
- [ ] Research into methods for possible implementation of a news widget.
- [ ] Outline possible solutions or explain methods/technologies we can use
- [ ] Bring in a possible skinny demo of what you've attempted

**Comment by khoadnguyen** [comment]
@raymondvooo Could you update with the status of this task?

**Comment by raymondvooo** [comment]
**Describe the feature briefly:**
Data model returned from rss feed has a data property that includes the summary, image, and link.


**What needs to be done?**
Summary needs to be parsed and separated from image and link so it can be formatted better

**Where does this appear?**
Dashboard

**Comment by khoadnguyen** [comment]
🔍
