### ISSUE TITLE
Dashboard: News Detail Page

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#208]
**Describe the feature briefly:**
We need a news detail page to accompany the news widget section that users can click on to view more about the article.

**What needs to be done?**

- [x] Wireframes for the news detail page (attach for review)
- [x] Page creation and layout, including any styling associated
- [x] Use mock data for now, we'll hook up to an RSS feed later  

**Where does this appear?**
Dashboard/New News page.

**Comment by raymondvooo** [comment]
https://app.moqups.com/raymondvooo/AKK9zUeU1C/view

**Comment by khoadnguyen** [comment]
👍
