### ISSUE TITLE
Profile: Wireframes for section layout

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#209]
**Describe the feature briefly:**
We're changing some of the edit functionality and reorganizing the profile section to be a bit cleaner. Please attach said wireframe to this issue when complete. Be prepared to show said wireframe in class.  

**What needs to be done?**
- [ ] Create a wireframe using something like [moqups](https://moqups.com/) and bring it in to class for review. Please look at existing functionality and design for context clues on what this section should look like.  

**Where does this appear?**
Profile page

**Comment by khoadnguyen** [comment]
@benjaminalfred Could you update with the status of this task?

**Comment by benjaminalfred** [comment]
![profile_wireframe](https://user-images.githubusercontent.com/5553103/49054265-91ef9f00-f1a8-11e8-858c-5b8e60a8c107.png)
