### ISSUE TITLE
Wiki: News & News Widget

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#240]
**What needs to be research?**
Documentation regarding the News page and Widget. Please make sure your documentation covers the following: 

- [x] What is your feature and what was the thinking behind adding it?
- [x] What unique technologies or methods did you use to create this feature? 
- [x] What are some caveats or pitfalls to be aware of? Are there any limitations that should be conveyed? 

**What are the deliverables?**

- [x] Documentation page within the wiki for the News Widget feature.

**Comment by raymondvooo** [comment]
https://github.com/SoftStackFactory/reboot/wiki/Component:-News-Widget

**Comment by khoadnguyen** [comment]
Same idea here, detail maybe the variables and what they're used for. I like that you included examples and code snippets, but you need to explain more about what the variables are used for.
