### ISSUE TITLE
Wiki: Resource Page

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#241]
**What needs to be research?**
Documentation regarding the Resources Page. Please make sure your documentation covers the following: 

- [x] What is your feature and what was the thinking behind adding it?
- [x] What unique technologies or methods did you use to create this feature? 
- [x] What are some caveats or pitfalls to be aware of? Are there any limitations that should be conveyed? 

**What are the deliverables?**

- [x] Documentation page within the wiki for the Resource Page feature.

**Comment by raymondvooo** [comment]
https://github.com/SoftStackFactory/reboot/wiki/Resources

**Comment by khoadnguyen** [comment]
Could you provided code examples of the line items you refer to. Specifically the functions and variables you are referencing. 

ex. `lowestScore` `lowestCat` etc.
