### ISSUE TITLE
Wiki: Timeline Page Changes

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#242]
**What needs to be research?**
Documentation regarding the Timeline Page Updates. Please make sure your documentation covers the following: 

- [ ] What is your feature and what was the thinking behind adding it?
- [ ] What unique technologies or methods did you use to create this feature? 
- [ ] What are some caveats or pitfalls to be aware of? Are there any limitations that should be conveyed? 

Since your feature is part of an existing wiki page, it possible that you can just add or edit the documentation to reflect the changes instead of creating a whole new Wiki Page.

**What are the deliverables?**

- [ ] Documentation page within the wiki for the Timeline Page updates (update existing) feature.

**Comment by papasmurf80** [comment]
Have made updates to Wiki - let me know what else I should add, or expand on.

**Comment by khoadnguyen** [comment]
Can you expand on the save functionality and functions/processes it goes through to grab and update data as well?
