### ISSUE TITLE
Wiki: Self Assessment Changes

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#243]
**What needs to be research?**
Documentation regarding the changes to the Self Assessment Page. Please make sure your documentation covers the following: 

- [x] What is your feature and what was the thinking behind adding it?
- [x] What unique technologies or methods did you use to create this feature? 
- [x] What are some caveats or pitfalls to be aware of? Are there any limitations that should be conveyed? 
- [x] Add any additional flow models based on changes to the way the user interacts with the page now. 

**What are the deliverables?**

- [x] Documentation page within the wiki for the Self Assessment Page updates feature.

**Comment by WarrenG8** [comment]
https://github.com/SoftStackFactory/reboot/wiki/Component:-Self-Assessment
