### ISSUE TITLE
Wiki: Charts History Page

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#244]
**What needs to be research?**
Documentation regarding the Charts History Page. Please make sure your documentation covers the following: 

- [x] What is your feature and what was the thinking behind adding it?
- [x] What unique technologies or methods did you use to create this feature? 
- [x] What are some caveats or pitfalls to be aware of? Are there any limitations that should be conveyed? 

**What are the deliverables?**

- [x] Documentation page within the wiki for the Charts History Page feature.

**Comment by brettwray** [comment]
https://github.com/SoftStackFactory/reboot/wiki/Page:-Chart-History
