### ISSUE TITLE
Offline Toast

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#268]
**Describe the bug**
A toast that appears when the app is checking for offline/online status needs to not display. Additionally, any console messages or other distracting notifications that arise, should be silenced. 

Let's take the toast off, but leave the check there to preserve the offline/online functionality.

**Additional context**
Bug we saw in class.

**Comment by Avilpa1** [comment]
Left existing toast in place but added a conditional statement to prevent multiple toast notifications from queuing up and firing at the same time.
