### ISSUE TITLE
Style Guide: Card Design

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#269]
**What needs to be research?**
Let's work on defining a coherent Card Styling for the app. The cards should encompass various use cases (use with images, use with charts, attached to buttons, with headers etc.). These should be put into a doc or specification people can refer to and defined (What font size is the header? What color is the card body font? etc.)

**What are the deliverables?**
A doc which clearly defines what styles for a card need to be use and how. This should be clear enough for someone picking up how they can replicate this card.

**Comment by khoadnguyen** [comment]
Please have a finalized specification doc for this ready for tonight's class.

**Comment by AlexRingrose** [comment]
[Document](https://docs.google.com/document/d/1v-u7B6nF5731bGQeMc8zU5FtW9byGZDfhwbd1h2NSPc/edit?usp=sharing)

This is my current style form

**Comment by khoadnguyen** [comment]
Great start! Let's try to tackle some more use cases: 

- [x] One with a picture that is edge to edge and content below with & w/o header
- [x] One with a picture aligned to the left or right with content wrapped around. One with and one w/o a header.

**Comment by AlexRingrose** [comment]
[Document](https://docs.google.com/document/d/1v-u7B6nF5731bGQeMc8zU5FtW9byGZDfhwbd1h2NSPc/edit?usp=sharing)  (link is the same)

I added info for the picture cards
