### ISSUE TITLE
Style Guide: Colors and Typography

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#270]
**What needs to be research?**
Currently we don't employ a consistent design language for the headers, colors, or typography. Let's get together a clear style guide for the colors and the typography that we can apply to all sections of the application. It should provide details on how to use headers/fonts and specify the combinations for how they need to be used. 

![style-guides](https://user-images.githubusercontent.com/2165265/52613557-3cd83680-2e43-11e9-958e-25320c65e520.jpg)

**What are the deliverables?**
At least a doc or something that details how the styles on the page need to be used. This should specify the font, color, size, spacing, etc. for each.

**Comment by bdarey** [comment]
Chose sizes for headers, body-text, and line-height. 
Chose primary and secondary colors. 
Having an issue trying to determine when to use the green or if we even need to. 
Let me know what else I need to include. 
Look at the glip file I shared with the class. I can't link it here.

**Comment by khoadnguyen** [comment]
Let's add link color in there as a styled piece as well. Please update the glip document.

**Comment by bdarey** [comment]
Added!
