### ISSUE TITLE
Dashboard: Styling

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#273]
**Describe the feature briefly:**
The dashboard needs some consistency with the headers and body text in the cards. Let's make them all have a uniform header1, header2, and body text styling. 

**What needs to be done?**
Using the default ionic header styles, set them all to use h2's for the main card header, h3 for any subheader and make sure the body font for the paragraphs are the same. 

**Where does this appear?**
Dashboard Page

**Comment by bdarey** [comment]
Fixed the inconsistencies. 
-Made card headers H2 and sub-headers H3. 
-Body text is now 20px. 
-updated background-color to match with the color scheme.

**Comment by khoadnguyen** [comment]
@bdarey did you have this in a PR ready to review?

**Comment by bdarey** [comment]
@khoadnguyen I accidentally assigned Kevin to this. I just forgot how to request someone to review something.

**Comment by khoadnguyen** [comment]
@bdarey You need to make a pull request before someone can have a look at your code. (https://github.com/SoftStackFactory/reboot#pull-requests).
