### ISSUE TITLE
Dashboard: Call to action

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#274]
**Describe the bug**
The call to actions on the cards need to be fixed. The call to actions should use the icons built into the default cards. See the "Map" card here and how the "Start" action is applied: 

https://ionicframework.com/docs/v3/components/#card-advanced-map

Apply this anywhere that has a call to action: "Learn More", "See what's next", etc.

**Comment by bdarey** [comment]
@khoadnguyen I don't think I am fully clear on the issue here. Do you want me to swap out the current arrow icon for a different one?
