### ISSUE TITLE
Timeline: Change to segment layout

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#285]
**Describe the feature briefly:**
For the Timeline page, we need a way to break out the information into more digestible sections. Currently the entire timeline is on huge layout. Instead, let's break each major section into a segment (https://ionicframework.com/docs/v3/components/#segment) with a segment menut at the top that is scrollable. 

<img width="1083" alt="screen shot 2019-02-18 at 9 21 19 pm" src="https://user-images.githubusercontent.com/2165265/52992029-f5622500-33c3-11e9-9600-abe62081cd6c.png">

Take a first pass at this according to the provided image.

**What needs to be done?**
Redo the layout of this section to use the ion segments to break apart the major sections into more digestible pieces. Within those sections, they should contain the main headers and checkmarks for those sections (each main section will have different headers and check mark items). 

**Where does this appear?**
Timeline Page

**Comment by khoadnguyen** [comment]
Per our conversation: Update the layout based on this feedback. The other categories need to display in a two column view.

![screen shot 2019-02-20 at 6 53 29 pm](https://user-images.githubusercontent.com/2165265/53140538-de494180-3541-11e9-910e-86be52322dfb.png)

**Comment by khoadnguyen** [comment]
Possible data structures: 

```
  public list1 = [
    {
      stepId: 1,
      subTitle: "Completing my paperwork",
      checkmark: true, 
    },
    {
      stepId: 2,
      subTitle: "Completing my paperwork",
      checkmark: true,
    },
    {
      stepId: 3,
      subTitle: "Mail stuff",
      checkmark: true,
    },
  ]

  public list2 = [
    {
      title: 'Understanding the process of separating',
      section: 'Getting Out',
      subItems: [
        {
          subTitle: "Completing my paperwork",
          checkmark: true, 
        },
        {
          subTitle: "Completing my paperwork",
          checkmark: true,
        },
      ]
    },
    {
      title: "Mail stuff",
      section: 'Getting Out',
      subItems: [
        {
          subTitle: "Completing my paperwork",
          checkmark: true, 
        },
        {
          subTitle: "Completing my paperwork",
          checkmark: true,
        },
      ]
    }
  ]
```

**Comment by Avilpa1** [comment]
![image](https://user-images.githubusercontent.com/40366920/53383381-45913800-392c-11e9-95d1-0756c87dea43.png)

**Comment by Avilpa1** [comment]
```
public goals = [
  { 
    goalName: 'Getting Out',
    subGoal: [
      {
        subGoalName: 'Understanding the process of separating',
        steps: [
          {
            step: 'Find out your separation date'
          },
          {
            step: 'Complete Pre-Separation Counseling'
          }
        ]
      },
      {
        subGoalName: 'Completing my paperwork',
        steps: [
          {
            step: 'Prepare a criterion-based Individual Transition Plan (ITP)'
          },
          {
            step: 'Complete a Continuum of Military Service Opportunity Counseling (Required Active Component Only)'
          }
        ]
      },
```
