### ISSUE TITLE
Dashboard: Separation Date

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#289]
**What needs to be done?**
Verify the separation date works. 1) Go through the flow and verify that the separation date through the wizard gets saved in the database. 2) Verify that the separation date on the dashboard accurately pulls in and calculates the separation date based on their entered date. 

**Where does this appear?**
Dashboard, Db values

**Comment by KevinChheang** [comment]
The separation date works. I verified by going through the flow of the wizard by filling out the form and verified that the date is accurately display on the Dashboard page.
