### ISSUE TITLE
Self Assessment: Layout and Logic refactor

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#299]
**Describe the feature briefly:**
Refer to the project charter for more information regarding the feature set. 

**What needs to be done?**
- [x] Modify the sort order functionality to use the existing array
- [x] Research options for source format ( Call / JSON / etc)
- [x] General layout improvements

**Where does this appear?**
Self Assessment

**Comment by AlexRingrose** [comment]
Layout & sort order changes are in pull requests #300 & #302 
Source format is probably more suited to a JSON file as it is unlikely to be changed frequently. If frequent changes are needed than a server call is more appropriate.

**Comment by khoadnguyen** [comment]
👍
