### ISSUE TITLE
History: User flow

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#321]
**What needs to be done?**
Document and create a user flow

**Where does this appear?**
Chart History Page

**Comment by AlexRingrose** [comment]
![Reboot_ History User Flow (1)](https://user-images.githubusercontent.com/43159722/54570279-2faaec00-499b-11e9-90dc-25189847b12c.png)

**Comment by AlexRingrose** [comment]
[FlowChart](https://docs.google.com/drawings/d/1DycoCAy0XKTX-mAJDo4IQWfavi0fy9VmQdzjTN63qTQ/edit?usp=sharing)

**Comment by khoadnguyen** [comment]
Looks good!
