### ISSUE TITLE
Dashboard: Chart

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#34]
**Describe the feature briefly:**
We need a functioning chart on the dashboard for now. Let's add it there.

**What needs to be done?**
Adding a functioning chartjs polar area chart to the dashboard. 

**Where does this appear?**
Dashboard Page

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/38 - link to PR that resolves this issue.
