### ISSUE TITLE
Transition: Landscape/Portrait View Responsiveness

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#42]
**What needs to be done?**
We want to make the application work on iPad Pro for both Landscape and Portrait Mode. Fix any visual inconsistencies you see and check that the layout is still good.

**Where does this appear?**
Transition Page

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/56 - link to PR that resolves this issue. Note that the PR is for a branch (#53 Transition: Adding Chart) that was intended for another issue. I just dealt with both issues at once on this single branch.
