### ISSUE TITLE
Profile: Landscape/Portrait View Responsiveness

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#45]
**What needs to be done?**
We want to make the application work on iPad Pro for both Landscape and Portrait Mode. Fix any visual inconsistencies you see and check that the layout is still good.

**Where does this appear?**
Profile Page

**Comment by khoadnguyen** [comment]
@iamalx What is the status of this page? Please make a PR before class.

**Comment by iamalx** [comment]
I am focusing on the wizard and having the form validation ready, including
limiting the ability to move to the next slide if the form is not filled
out. The profile is easier. I will have that later tonight.

**Comment by khoadnguyen** [comment]
@iamalx is this complete yet? We need to have this in since it is a week old at this point.

**Comment by iamalx** [comment]
Yes, It was completed last week. I thought I did a pull request, but I think it is in another branch. I will see what happen

**Comment by iamalx** [comment]
I don't know what happened, but apparently I did a pull request called "45 profile portrait responsive #71"  and you already reviewed it an accepted it.

**Comment by khoadnguyen** [comment]
Interesting we can probably close this one today then. Were the changes inside: https://github.com/SoftStackFactory/reboot/pull/100 for the profile page stylesheet relevant to this at all?

**Comment by iamalx** [comment]
Do you mean changes in the "65 wizard validation error messages".. i don't think I made a commit to this page in here for a wizard page... but I do remember that somehow when I did a git status, I saw the profile file in the list. But I added the files manually (i.e. add <wizard-file-name> <wizard-file>), excluding the profile page... either way, those changes can be deleted.
