### ISSUE TITLE
Dashboard: Landscape/Portrait View Responsiveness

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#47]
**What needs to be done?**
We want to make the application work on iPad Pro for both Landscape and Portrait Mode. Fix any visual inconsistencies you see and check that the layout is still good.

**Where does this appear?**
Dashboard Page

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/55 - link to the PR that resolves this issue.
