### ISSUE TITLE
Wizard: Menu

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#50]
**Describe the bug**
The wizard menu with the forward and back buttons disappears behind the menu occasionally.

**Expected behavior**
The subpage menu should appear more consistently. 

**Screenshots**
![screen shot 2018-09-26 at 9 27 32 pm](https://user-images.githubusercontent.com/2165265/46123386-00c57180-c1d3-11e8-9986-90aa3775a637.png)

**Comment by iamalx** [comment]
issue solved in branch 65, commit "#50 fixed nav-bar bug by changing fixed position to absolute"
