### ISSUE TITLE
Dashboard: Chart Labels

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#51]
**Describe the bug**
The chart labels ideally should have a clear background and no border.

**Screenshots**
![screen shot 2018-09-26 at 9 30 22 pm](https://user-images.githubusercontent.com/2165265/46123447-64e83580-c1d3-11e8-90e1-26e0ecce64e0.png)

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/57 - link to the PR that resolves this issue
