### ISSUE TITLE
Profile: Alignment

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#52]
**Describe the bug**
There are some alignment inconsistencies with the profile page. The name/email section borders are not aligned on one side. Additionally, the buttons look askew. 

**Expected behavior**
The borders should match and be consistent. The buttons should be aligned and evenly spaced out, with equal spacing around both. 

**Screenshots**
![screen shot 2018-09-26 at 9 32 39 pm](https://user-images.githubusercontent.com/2165265/46123486-b5f82980-c1d3-11e8-8ef7-42d771c7f7f5.png)

**Comment by iamalx** [comment]
#45 issue already solved in #45 Profile: Landscape/Portrait View Responsiveness....  buttons and personal information section solved.
