### ISSUE TITLE
Transition: Adding Chart

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#53]
**Describe the feature briefly:**
We need to actually add the chart on to the transition page and make it interactive.

**What needs to be done?**
Add the chart and slider to the the transition page.

**Where does this appear?**
Transition Page.

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/56 - link to the PR that resolves this issue

**Comment by awstin17** [comment]
https://www.joshmorony.com/adding-responsive-charts-graphs-to-ionic-2-applications/ - link to the josh morony article that solved disappearing chart bug
