### ISSUE TITLE
Login: Backend functionality & updates

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#66]
**Describe the feature briefly:**
We need a couple things ironed out for the Login page. Additionally, we'll need to start on functionality for the login/authentication with the backend. 

**What needs to be done?**
1. For the icons, make sure they are styled and aligned for landscape and tablet views. (don't use absolute positioning)
2. The inputs need to be ion-input to take advantage of the form group and ionic form validation.
3. The login page needs to actually route and authenticate a real user from the database. Add functionality for this page to be able to do that. It should route users to the Dashboard after successful login.
4. The login fields should validate and offer error messages if the user incorrectly inputs something.
5. Any links to other pages should be filled out ie. Register page (button). 

**Where does this appear?**
Login page

**Comment by awstin17** [comment]
https://github.com/SoftStackFactory/reboot/pull/97 - link to the PR that resolves this issue
